// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gikjchebyjmysihbvjvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpa2pjaGVieWpteXNpaGJ2anZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTI3ODgsImV4cCI6MjA3NTY4ODc4OH0.0vZE_NOVaLsGW80D-qzcQy_yiloNg7qcuXH-ipZfUR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});